"""Binary export via PyInstaller (LL6).

Turns a scaffolded project into a standalone executable by writing a
temporary ``.spec`` file that describes the entry point + data files,
then invoking PyInstaller.

PyInstaller is *soft-imported* — if it is not installed we degrade
gracefully and set ``ExportResult.warnings`` with an actionable hint
(``pip install pyinstaller``) rather than raising.

The build never runs when ``dry_run=True`` — useful for CI / tests that
want to exercise the spec generator without the (multi-minute)
PyInstaller step.
"""
from __future__ import annotations

import importlib.util
import os
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Sequence


__all__ = ["BinaryExporter", "BinaryExportResult", "pyinstaller_available"]


def pyinstaller_available() -> bool:
    """Return True if the ``PyInstaller`` package can be imported."""
    return importlib.util.find_spec("PyInstaller") is not None


@dataclass
class BinaryExportResult:
    binary_path: Path | None
    spec_path: Path | None
    size_bytes: int = 0
    log: str = ""
    warnings: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    succeeded: bool = False
    skipped_reason: str | None = None


_SPEC_TEMPLATE = '''\
# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by slappyengine.exporter.BinaryExporter

block_cipher = None

a = Analysis(
    [{entry!r}],
    pathex=[{project_dir!r}],
    binaries=[],
    datas={datas!r},
    hiddenimports={hiddenimports!r},
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name={name!r},
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console={console!r},
    icon={icon!r},
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
'''


class BinaryExporter:
    """Build a standalone binary from a scaffolded project."""

    def __init__(self, *, hidden_imports: Sequence[str] | None = None) -> None:
        # Slappyengine ships C-extensions and yaml — surface them by default
        # so PyInstaller's static analysis picks them up.
        default_hidden = [
            "slappyengine",
            "slappyengine._core",
            "yaml",
        ]
        self.hidden_imports = list(hidden_imports or default_hidden)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def export(
        self,
        project_dir: str | Path,
        output_path: str | Path,
        *,
        platform: str = "auto",
        console: bool = False,
        icon: str | Path | None = None,
        dry_run: bool = False,
        main_script: str = "main.py",
        name: str | None = None,
    ) -> BinaryExportResult:
        project_dir = Path(project_dir).resolve()
        output_path = Path(output_path).resolve()

        result = BinaryExportResult(binary_path=None, spec_path=None)

        if not project_dir.is_dir():
            result.errors.append(f"project directory does not exist: {project_dir}")
            return result

        entry = project_dir / main_script
        if not entry.is_file():
            result.errors.append(f"main script not found: {entry}")
            return result

        # Emit spec file so that even when PyInstaller is unavailable we
        # leave behind an artefact the user can hand to PyInstaller
        # manually.
        output_path.mkdir(parents=True, exist_ok=True)
        spec_path = self._write_spec(
            project_dir=project_dir,
            entry=entry,
            output_dir=output_path,
            console=console,
            icon=icon,
            name=name or project_dir.name,
        )
        result.spec_path = spec_path

        if not pyinstaller_available():
            result.skipped_reason = "PyInstaller not installed"
            result.warnings.append(
                "PyInstaller is not installed — install it with:\n"
                "    pip install pyinstaller\n"
                f"Spec file written to {spec_path}"
            )
            return result

        if dry_run:
            result.skipped_reason = "dry_run=True"
            result.warnings.append("dry_run=True — spec generated but PyInstaller not invoked")
            return result

        # Import target-specific flags (used as hint, not enforced)
        from . import platform_targets

        target = platform_targets.get_target(platform)
        target_flags = list(target.get("pyinstaller_flags", []))

        cmd = [
            sys.executable,
            "-m",
            "PyInstaller",
            "--noconfirm",
            "--distpath",
            str(output_path / "dist"),
            "--workpath",
            str(output_path / "build"),
            "--specpath",
            str(output_path),
            *target_flags,
            str(spec_path),
        ]

        try:
            completed = subprocess.run(
                cmd,
                cwd=str(project_dir),
                capture_output=True,
                text=True,
                timeout=1800,
            )
        except subprocess.TimeoutExpired as exc:
            result.errors.append(f"PyInstaller timed out after {exc.timeout}s")
            return result
        except FileNotFoundError as exc:
            result.errors.append(f"failed to invoke PyInstaller: {exc}")
            return result

        result.log = (completed.stdout or "") + "\n" + (completed.stderr or "")

        if completed.returncode != 0:
            result.errors.append(
                f"PyInstaller exited {completed.returncode} — see log for details"
            )
            return result

        # Locate produced binary
        exe_ext = target.get("executable_ext", "")
        binary_name = f"{name or project_dir.name}{exe_ext}"
        candidate = output_path / "dist" / binary_name
        if candidate.exists():
            result.binary_path = candidate
            try:
                result.size_bytes = candidate.stat().st_size
            except OSError:
                pass
            result.succeeded = True
        else:
            result.errors.append(
                f"expected binary not found at {candidate}; check log"
            )
        return result

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------
    def _write_spec(
        self,
        *,
        project_dir: Path,
        entry: Path,
        output_dir: Path,
        console: bool,
        icon: str | Path | None,
        name: str,
    ) -> Path:
        datas: list[tuple[str, str]] = []
        for data_dir in ("assets", "scenes"):
            src = project_dir / data_dir
            if src.exists():
                datas.append((str(src), data_dir))
        for data_file in ("config.yaml", "slappyproject.yaml"):
            src = project_dir / data_file
            if src.is_file():
                datas.append((str(src), "."))

        spec_body = _SPEC_TEMPLATE.format(
            entry=str(entry),
            project_dir=str(project_dir),
            datas=datas,
            hiddenimports=list(self.hidden_imports),
            name=name,
            console=console,
            icon=str(icon) if icon else None,
        )
        spec_path = output_dir / f"{name}.spec"
        spec_path.write_text(spec_body, encoding="utf-8")
        return spec_path
