// Auto-generated by MaterialGraphBridge.emit_full_shader

struct MaterialOutput {
    base_color: vec3<f32>,
    metallic: f32,
    roughness: f32,
    emissive: vec3<f32>,
    normal: vec3<f32>,
};

@group(0) @binding(0) var<uniform> u_albedo: f32;
@group(0) @binding(1) var<uniform> u_albedo_sampler: f32;

@fragment
fn fs_main() -> @location(0) vec4<f32> {
    var material_output: MaterialOutput;
    material_output.base_color = vec3<f32>(1.0, 1.0, 1.0);
    material_output.metallic = 0.0;
    material_output.roughness = 0.5;
    material_output.emissive = vec3<f32>(0.0, 0.0, 0.0);
    material_output.normal = vec3<f32>(0.0, 0.0, 1.0);
    let uv_off_1 = vec2<f32>(0.0, 0.0) + vec2<f32>(0.0, 0.0);
    let kf_2 = f32(0.35);
    let tex_3 = textureSample(u_albedo, u_albedo_sampler, uv_off_1);
    let add_4 = (tex_3) + (kf_2);
    material_output.base_color = vec3<f32>(1.0, 1.0, 1.0);
    material_output.metallic = 0.0;
    material_output.roughness = add_4;
    material_output.emissive = vec3<f32>(0.0, 0.0, 0.0);
    material_output.normal = vec3<f32>(0.0, 0.0, 1.0);
    let fs_out = vec4<f32>(material_output.base_color, 1.0);
    return fs_out;
}