// Auto-generated by MaterialGraphBridge.emit_full_shader

struct MaterialOutput {
    base_color: vec3<f32>,
    metallic: f32,
    roughness: f32,
    emissive: vec3<f32>,
    normal: vec3<f32>,
};

@fragment
fn fs_main() -> @location(0) vec4<f32> {
    var material_output: MaterialOutput;
    material_output.base_color = vec3<f32>(1.0, 1.0, 1.0);
    material_output.metallic = 0.0;
    material_output.roughness = 0.5;
    material_output.emissive = vec3<f32>(0.0, 0.0, 0.0);
    material_output.normal = vec3<f32>(0.0, 0.0, 1.0);
    let const_1 = vec3<f32>(0.2, 0.4, 0.9);
    let fresnel_2 = pow(1.0 - clamp(dot(vec3<f32>(0.0, 0.0, 1.0), vec3<f32>(0.0, 0.0, 1.0)), 0.0, 1.0), 5.0) * 1.5;
    let kf_3 = f32(0.8);
    let mul_4 = (fresnel_2) * (kf_3);
    material_output.base_color = const_1;
    material_output.metallic = 0.0;
    material_output.roughness = mul_4;
    material_output.emissive = vec3<f32>(0.0, 0.0, 0.0);
    material_output.normal = vec3<f32>(0.0, 0.0, 1.0);
    let fs_out = vec4<f32>(material_output.base_color, 1.0);
    return fs_out;
}