// Auto-generated by MaterialGraphBridge.emit_full_shader

struct MaterialOutput {
    base_color: vec3<f32>,
    metallic: f32,
    roughness: f32,
    emissive: vec3<f32>,
    normal: vec3<f32>,
};

@group(0) @binding(0) var perlin2d: texture_2d<f32>;
@group(0) @binding(1) var<uniform> u_time: f32;

@fragment
fn fs_main() -> @location(0) vec4<f32> {
    var material_output: MaterialOutput;
    material_output.base_color = vec3<f32>(1.0, 1.0, 1.0);
    material_output.metallic = 0.0;
    material_output.roughness = 0.5;
    material_output.emissive = vec3<f32>(0.0, 0.0, 0.0);
    material_output.normal = vec3<f32>(0.0, 0.0, 1.0);
    let time_1 = u_time;
    var perlin_acc_3: f32 = 0.0;
    var perlin_amp_4: f32 = 1.0;
    var perlin_f_5: f32 = 4.0;
    for (var i: i32 = 0; i < 3; i = i + 1) {
        perlin_acc_3 = perlin_acc_3 + perlin2d(vec2<f32>(0.0, 0.0) * perlin_f_5) * perlin_amp_4;
        perlin_f_5 = perlin_f_5 * 2.0;
        perlin_amp_4 = perlin_amp_4 * 0.5;
    }
    let perlin_2 = perlin_acc_3;
    material_output.base_color = vec3<f32>(1.0, 1.0, 1.0);
    material_output.metallic = time_1;
    material_output.roughness = 0.5;
    material_output.emissive = vec3<f32>(0.0, 0.0, 0.0);
    material_output.normal = vec3<f32>(0.0, 0.0, 1.0);
    var ramp_col_7: vec4<f32> = vec4<f32>(0.05, 0.1, 0.25, 1.0);
    if (perlin_2 >= 0.0) {
        let local = clamp((perlin_2 - 0.0) / 0.5, 0.0, 1.0);
        ramp_col_7 = mix(ramp_col_7, vec4<f32>(0.4, 0.5, 0.9, 1.0), local);
    }
    if (perlin_2 >= 0.5) {
        let local = clamp((perlin_2 - 0.5) / 0.5, 0.0, 1.0);
        ramp_col_7 = mix(ramp_col_7, vec4<f32>(1.0, 0.9, 0.6, 1.0), local);
    }
    let ramp_6 = ramp_col_7;
    let fs_out = vec4<f32>(material_output.base_color, 1.0);
    return fs_out;
}