"""Build script generator — reads project.yml and writes platform-specific build scripts.

Creates ``build_<platform>.bat`` (Windows) and ``build_<platform>.sh`` (POSIX)
in the project root.  Run via ``slap build`` or call ``generate_build_scripts()``.

Supported platform targets:
    windows — PyInstaller EXE via maturin build then pyinstaller
    linux   — PyInstaller ELF binary
    macos   — PyInstaller .app bundle
    web     — Emscripten/Pyodide bundle (experimental)

Content encryption is auto-wired when ``project.yml`` has
``encryption.enabled: true`` — the build script calls
``python -m slappyengine.content_encrypt`` to encrypt the assets directory
before packaging.

Usage::

    from slappyengine.build_gen import generate_build_scripts
    generate_build_scripts("project.yml", output_dir=".")
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import yaml


# ---------------------------------------------------------------------------
# Script templates
# ---------------------------------------------------------------------------

_BAT_HEADER = """\
@echo off
rem Auto-generated by SlapPyEngine build_gen — do not edit by hand.
rem Re-run: python -m slappyengine.build_gen
setlocal
set PROJECT_DIR=%~dp0
"""

_SH_HEADER = """\
#!/usr/bin/env bash
# Auto-generated by SlapPyEngine build_gen — do not edit by hand.
# Re-run: python -m slappyengine.build_gen
set -e
PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
"""

_BAT_MATURIN = """\
echo [build] Compiling Rust extension (maturin)...
maturin build --release --out dist_wheel/
if errorlevel 1 ( echo [ERROR] maturin build failed & exit /b 1 )
"""

_SH_MATURIN = """\
echo "[build] Compiling Rust extension (maturin)..."
maturin build --release --out dist_wheel/
"""

_BAT_PYINSTALLER = """\
echo [build] Packaging with PyInstaller...
pip install --quiet --find-links dist_wheel/ slappy-engine
pyinstaller --onefile --name "{name}" {entry}
if errorlevel 1 ( echo [ERROR] PyInstaller failed & exit /b 1 )
echo [build] Done. Output: dist\\{name}.exe
"""

_SH_PYINSTALLER = """\
echo "[build] Packaging with PyInstaller..."
pip install --quiet --find-links dist_wheel/ slappy-engine
pyinstaller --onefile --name "{name}" {entry}
echo "[build] Done. Output: dist/{name}"
"""

_BAT_ENCRYPT = """\
echo [build] Encrypting assets...
python -m slappyengine.content_encrypt encrypt assets dist_assets {entry} --key-env SLAP_CONTENT_KEY
if errorlevel 1 ( echo [WARN] Encryption step failed — assets NOT encrypted )
"""

_SH_ENCRYPT = """\
echo "[build] Encrypting assets..."
python -m slappyengine.content_encrypt encrypt assets dist_assets {entry} --key-env SLAP_CONTENT_KEY || echo "[WARN] Encryption step failed — assets NOT encrypted"
"""

_BAT_MACOS_BUNDLE = """\
echo [build] Creating .app bundle...
pyinstaller --onefile --windowed --name "{name}" {entry}
echo [build] Done. Output: dist/{name}.app
"""

_SH_WEB = """\
echo "[build] Building for web (Emscripten/Pyodide)..."
echo "[WARN] Web target is experimental. Requires Emscripten + Pyodide."
python tools/build_web.py --entry {entry} --out dist_web/
echo "[build] Done. Output: dist_web/"
"""


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

def generate_build_scripts(
    project_yml: str | Path = "project.yml",
    output_dir: str | Path = ".",
) -> list[Path]:
    """Read *project_yml* and write build scripts for each declared platform.

    Parameters
    ----------
    project_yml:
        Path to the project YAML file.
    output_dir:
        Directory to write the generated scripts into.

    Returns
    -------
    list[Path]
        Paths of all generated script files.
    """
    yml_path = Path(project_yml)
    if not yml_path.exists():
        raise FileNotFoundError(f"project.yml not found at {yml_path}")

    with yml_path.open("r", encoding="utf-8") as fh:
        proj = yaml.safe_load(fh) or {}

    name = proj.get("name", "game").replace(" ", "_")
    entry = proj.get("entry", "main.py")
    platforms: list[str] = proj.get("platforms", ["windows"])
    enc_enabled = proj.get("encryption", {}).get("enabled", False)

    out_dir = Path(output_dir)
    generated: list[Path] = []

    for platform in platforms:
        platform = platform.strip().lower()
        if platform == "windows":
            p = _write_bat(out_dir / "build_windows.bat", name, entry, enc_enabled)
        elif platform == "linux":
            p = _write_sh(out_dir / "build_linux.sh", name, entry, enc_enabled, platform)
        elif platform == "macos":
            p = _write_sh(out_dir / "build_macos.sh", name, entry, enc_enabled, platform)
        elif platform == "web":
            p = _write_sh(out_dir / "build_web.sh", name, entry, enc_enabled, "web")
        else:
            import warnings
            warnings.warn(f"Unknown platform {platform!r} — skipped")
            continue
        generated.append(p)
        print(f"[build_gen] Wrote {p}")

    return generated


def _write_bat(path: Path, name: str, entry: str, encrypt: bool) -> Path:
    parts = [_BAT_HEADER, _BAT_MATURIN]
    if encrypt:
        parts.append(_BAT_ENCRYPT.format(entry=entry))
    parts.append(_BAT_PYINSTALLER.format(name=name, entry=entry))
    parts.append("endlocal\n")
    path.write_text("".join(parts), encoding="utf-8")
    return path


def _write_sh(path: Path, name: str, entry: str, encrypt: bool, platform: str) -> Path:
    parts = [_SH_HEADER, _SH_MATURIN]
    if encrypt:
        parts.append(_SH_ENCRYPT.format(entry=entry))
    if platform == "macos":
        parts.append(_BAT_MACOS_BUNDLE.format(name=name, entry=entry))
    elif platform == "web":
        parts.append(_SH_WEB.format(entry=entry))
    else:
        parts.append(_SH_PYINSTALLER.format(name=name, entry=entry))
    path.write_text("".join(parts), encoding="utf-8")
    try:
        os.chmod(path, 0o755)
    except Exception:
        pass  # Windows doesn't support chmod
    return path


# ---------------------------------------------------------------------------
# CLI entry point: python -m slappyengine.build_gen
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Generate build scripts from project.yml")
    parser.add_argument("--project", default="project.yml", help="Path to project.yml")
    parser.add_argument("--out", default=".", help="Output directory for scripts")
    args = parser.parse_args()
    paths = generate_build_scripts(args.project, args.out)
    print(f"Generated {len(paths)} script(s).")
