//! Skeletal skinning.
//!
//! Sprint 5 target. Bone-palette buffer + skinning WGSL invoked by
//! the G-buffer + forward vertex shaders when the mesh has a skeleton
//! attached.

use glam::Mat4;

pub mod config {
    //! Single source of truth for skinning shader compile-time
    //! constants. Every magic number the WGSL shader consults through
    //! a `const` binding lives here.

    /// Weights + indices per vertex. Nova3D shipped 4 (matches Assimp
    /// standard). Increasing requires vertex layout + palette lookup
    /// changes across every skinning-capable shader.
    pub const MAX_WEIGHTS_PER_VERTEX: u32 = 4;

    /// Max bones per palette. 256 covers characters + creatures;
    /// vehicles / rigged crowds push higher via multiple palettes.
    pub const MAX_BONES_PER_PALETTE: u32 = 256;

    /// Emit the WGSL `const` header prepended to `skinning.wgsl`.
    pub fn wgsl_define_block() -> String {
        format!(
            "// GENERATED by pharos_render::skinning::config::wgsl_define_block\n\
             const SKIN_MAX_WEIGHTS_PER_VERTEX: u32 = {wpv}u;\n\
             const SKIN_MAX_BONES_PER_PALETTE: u32 = {bpp}u;\n",
            wpv = MAX_WEIGHTS_PER_VERTEX,
            bpp = MAX_BONES_PER_PALETTE,
        )
    }
}

#[derive(Debug, Clone)]
pub struct Skeleton {
    pub bones: Vec<Bone>,
}

#[derive(Debug, Clone)]
pub struct Bone {
    pub parent: Option<u32>,
    pub inverse_bind: Mat4,
    pub local: Mat4,
}

impl Skeleton {
    /// Flatten the current bone poses into a palette matrix array
    /// suitable for GPU upload as a storage buffer.
    pub fn bone_palette(&self) -> Vec<Mat4> {
        let mut world = Vec::with_capacity(self.bones.len());
        for bone in &self.bones {
            let parent_world = bone
                .parent
                .and_then(|p| world.get(p as usize).copied())
                .unwrap_or(Mat4::IDENTITY);
            world.push(parent_world * bone.local);
        }
        // Skinning matrix = world_pose * inverse_bind.
        world
            .iter()
            .zip(self.bones.iter())
            .map(|(w, b)| *w * b.inverse_bind)
            .collect()
    }
}
