//! PBF GPU compute pipeline — Sprint 7.
//!
//! Wraps `shaders/pbf_step.wgsl`. Four compute entry points:
//! cs_predict, cs_hash, cs_solve, cs_integrate. The scheduler runs
//! them in order N_ITERATIONS times per frame; ping-pong is handled
//! implicitly by the write-back-to-same-buffer pattern (safe because
//! each stage reads-then-writes non-overlapping fields).
//!
//! Sprint 4 SSoT refactor: pipeline-compile-time constants (workgroup
//! size, max neighbours per cell, iteration count) live in
//! [`config::wgsl_define_block`] and are prepended to the shader
//! source at pipeline creation. The WGSL file consumes them by name.

pub mod config {
    //! Single source of truth for PBF pipeline compile-time constants.
    //!
    //! Every magic number the shader consults through a `const` binding
    //! lives here. `wgsl_define_block(params)` emits the WGSL header
    //! prepended to `pbf_step.wgsl` at pipeline creation.

    /// GPU workgroup size for particle iteration. Must divide the SM
    /// warp size; 64 is the sweet spot on desktop GPUs (Nova3D
    /// telemetry showed 32 leaves lanes idle, 128 spills registers).
    pub const WORKGROUP_SIZE: u32 = 64;

    /// Max particles per spatial-hash cell before overflow. Nova3D
    /// tuned this at 32 for water at 8x rest density; higher wastes
    /// bind-group memory.
    pub const MAX_PARTICLES_PER_CELL: u32 = 32;

    /// Density-constraint projection iteration count. Nova3D shipped 4
    /// as the visual sweet spot (< 3 = compressible, > 6 = diminishing).
    pub const SOLVER_ITERATIONS: u32 = 4;

    /// Emit the WGSL `const` header prepended to `pbf_step.wgsl`.
    pub fn wgsl_define_block() -> String {
        format!(
            "// GENERATED by pharos_render::compute::pbf::config::wgsl_define_block\n\
             const PBF_WORKGROUP_SIZE: u32 = {ws}u;\n\
             const PBF_MAX_PARTICLES_PER_CELL: u32 = {mp}u;\n\
             const PBF_SOLVER_ITERATIONS: u32 = {si}u;\n",
            ws = WORKGROUP_SIZE,
            mp = MAX_PARTICLES_PER_CELL,
            si = SOLVER_ITERATIONS,
        )
    }
}

pub struct PbfGpu {
    pub predict: wgpu::ComputePipeline,
    pub hash: wgpu::ComputePipeline,
    pub solve: wgpu::ComputePipeline,
    pub integrate: wgpu::ComputePipeline,
}

impl PbfGpu {
    pub fn new(device: &wgpu::Device) -> Self {
        let src = format!(
            "{defines}{body}",
            defines = config::wgsl_define_block(),
            body = include_str!("../../shaders/pbf_step.wgsl"),
        );
        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("pharos_render.compute.pbf.shader"),
            source: wgpu::ShaderSource::Wgsl(std::borrow::Cow::Owned(src)),
        });
        let make = |entry: &str, label: &str| {
            device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
                label: Some(label),
                layout: None,
                module: &shader,
                entry_point: entry,
                compilation_options: Default::default(),
            })
        };
        PbfGpu {
            predict:   make("cs_predict",   "pharos_render.compute.pbf.predict"),
            hash:      make("cs_hash",      "pharos_render.compute.pbf.hash"),
            solve:     make("cs_solve",     "pharos_render.compute.pbf.solve"),
            integrate: make("cs_integrate", "pharos_render.compute.pbf.integrate"),
        }
    }
}
