//! Softbody XPBD GPU compute pipeline — Sprint 7.
//!
//! Three entry points: cs_predict, cs_solve_beams, cs_integrate. The
//! solver scheduler runs solve_beams N_ITERATIONS times between
//! predict and integrate.
//!
//! Sprint 4 SSoT refactor: pipeline-compile-time constants (workgroup
//! size, solver iterations, gravity fallback) live in
//! [`config::wgsl_define_block`] and are prepended to the shader
//! source at pipeline creation.

pub mod config {
    //! Single source of truth for softbody pipeline compile-time
    //! constants. Every magic number the shader consults through a
    //! `const` binding lives here.

    /// GPU workgroup size for node/beam iteration. 64 matches the PBF
    /// solver — same sweet spot on desktop hardware.
    pub const WORKGROUP_SIZE: u32 = 64;

    /// Distance-constraint iterations per substep. Nova3D shipped 6
    /// (visual sweet spot: < 4 = squishy, > 8 = diminishing).
    pub const SOLVER_ITERATIONS: u32 = 6;

    /// Emit the WGSL `const` header prepended to `softbody_step.wgsl`.
    pub fn wgsl_define_block() -> String {
        format!(
            "// GENERATED by pharos_render::compute::softbody::config::wgsl_define_block\n\
             const SB_WORKGROUP_SIZE: u32 = {ws}u;\n\
             const SB_SOLVER_ITERATIONS: u32 = {si}u;\n",
            ws = WORKGROUP_SIZE,
            si = SOLVER_ITERATIONS,
        )
    }
}

pub struct SoftbodyGpu {
    pub predict: wgpu::ComputePipeline,
    pub solve_beams: wgpu::ComputePipeline,
    pub integrate: wgpu::ComputePipeline,
}

impl SoftbodyGpu {
    pub fn new(device: &wgpu::Device) -> Self {
        let src = format!(
            "{defines}{body}",
            defines = config::wgsl_define_block(),
            body = include_str!("../../shaders/softbody_step.wgsl"),
        );
        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("pharos_render.compute.softbody.shader"),
            source: wgpu::ShaderSource::Wgsl(std::borrow::Cow::Owned(src)),
        });
        let make = |entry: &str, label: &str| {
            device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
                label: Some(label),
                layout: None,
                module: &shader,
                entry_point: entry,
                compilation_options: Default::default(),
            })
        };
        SoftbodyGpu {
            predict:     make("cs_predict",     "pharos_render.compute.softbody.predict"),
            solve_beams: make("cs_solve_beams", "pharos_render.compute.softbody.solve_beams"),
            integrate:   make("cs_integrate",   "pharos_render.compute.softbody.integrate"),
        }
    }
}
