//! VCR Single-Source-of-Truth constants (Sprint 6 target).
//!
//! Mirrors Nova3D's `VCRConfig.hpp`. Sprint 6 wires shader `#define`
//! block injection at WGSL compile time.

/// Preset controlling K, precision, resolution, temporal reuse.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Preset {
    Off,
    Compat,     // K=2, unorm8, 0.25x res, no temporal
    Standard,   // K=4, fp16+oct16, 0.5x res, temporal ON
    Cinematic,  // K=8, fp32, 1.0x res, temporal ON
}

#[derive(Debug, Clone, Copy)]
pub struct PresetParams {
    pub k_slots: u32,
    pub res_scale: f32,
    pub temporal_reuse: bool,
    pub precision: Precision,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Precision {
    Micro,   // unorm8 packed accumulators, 24 B / slot
    Half,    // fp16 pos + oct16 dir, 32 B / slot (default)
    Full,    // fp32 pos + fp32 dir, 48 B / slot (cinematic)
}

impl Preset {
    pub fn params(self) -> PresetParams {
        match self {
            Preset::Off => PresetParams { k_slots: 0, res_scale: 0.0, temporal_reuse: false, precision: Precision::Micro },
            Preset::Compat => PresetParams { k_slots: 2, res_scale: 0.25, temporal_reuse: false, precision: Precision::Micro },
            Preset::Standard => PresetParams { k_slots: 4, res_scale: 0.5, temporal_reuse: true, precision: Precision::Half },
            Preset::Cinematic => PresetParams { k_slots: 8, res_scale: 1.0, temporal_reuse: true, precision: Precision::Full },
        }
    }
}

/// WRS merge threshold — slots below this cumulative alpha get dropped
/// during Stage 3 (Weighted Reservoir Sampling merge).
pub const ALPHA_DROP_THRESHOLD: f32 = 0.02;

/// Coverage buffer opt-out threshold — pixel skips rasterization once
/// aggregate alpha across all K slots reaches this bound.
pub const COVERAGE_OPT_OUT: f32 = 0.98;

/// Emit the WGSL `#define` header that pipeline builders inject at
/// shader compile time. Keeps all numeric constants in one place.
pub fn wgsl_define_block(p: PresetParams) -> String {
    format!(
        r#"// GENERATED by pharos_render::vcr::config::wgsl_define_block
const VCR_K_SLOTS: u32 = {k}u;
const VCR_RES_SCALE: f32 = {r};
const VCR_TEMPORAL_ENABLED: bool = {t};
const VCR_ALPHA_DROP_THRESHOLD: f32 = {ath};
const VCR_COVERAGE_OPT_OUT: f32 = {cop};
"#,
        k = p.k_slots,
        r = p.res_scale,
        t = p.temporal_reuse,
        ath = ALPHA_DROP_THRESHOLD,
        cop = COVERAGE_OPT_OUT,
    )
}
