// Auto-generated by MaterialGraphBridge.emit_full_shader

struct MaterialOutput {
    base_color: vec3<f32>,
    metallic: f32,
    roughness: f32,
    emissive: vec3<f32>,
    normal: vec3<f32>,
};

@fragment
fn fs_main() -> @location(0) vec4<f32> {
    var material_output: MaterialOutput;
    material_output.base_color = vec3<f32>(1.0, 1.0, 1.0);
    material_output.metallic = 0.0;
    material_output.roughness = 0.5;
    material_output.emissive = vec3<f32>(0.0, 0.0, 0.0);
    material_output.normal = vec3<f32>(0.0, 0.0, 1.0);
    let const_1 = vec3<f32>(0.9, 0.2, 0.15);
    material_output.base_color = const_1;
    material_output.metallic = 0.0;
    material_output.roughness = 0.5;
    material_output.emissive = vec3<f32>(0.0, 0.0, 0.0);
    material_output.normal = vec3<f32>(0.0, 0.0, 1.0);
    let fs_out = vec4<f32>(material_output.base_color, 1.0);
    return fs_out;
}