"""Sprint 2 anchor test — cross-game sprite quality audit (engine side).

Iterates the engine's own bundled baseline PNGs under
``python/pharos_engine/testing/baselines/`` plus any source sprites that
might land under ``tests/visual/reference/`` or a future repo-root
``assets/`` tree, and asserts that none of them earn the ``critical``
recommendation from :func:`pharos_engine.tools.sprite_audit.assess_quality`.

The audit thresholds (alpha coverage, saturation, minimum dimension) come
from the in-tree sprite audit tool — see ``docs/sprite_audit_recipe.md``
for the human-readable procedure and ``H:/tmp/sprite_audit_sprint2/`` for
the full inventory report generated by the sprint.

A sprite that is *intentionally* a placeholder (e.g. ``placeholder_*.png``)
is marked ``xfail`` rather than failing the suite — that keeps the door
open for future placeholder fixtures without breaking CI.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from pharos_engine.tools.sprite_audit import (
    SpriteInventoryEntry,
    assess_quality,
    inventory_sprites,
)


_REPO_ROOT = Path(__file__).resolve().parent.parent.parent

_BASELINES_DIR = _REPO_ROOT / "python" / "pharos_engine" / "testing" / "baselines"
_VISUAL_REF_DIR = _REPO_ROOT / "PharosEngineTests" / "tests" / "visual" / "reference"
_ASSETS_DIR = _REPO_ROOT / "assets"


def _gather_entries() -> list[SpriteInventoryEntry]:
    """Collect every PNG the sprint scope cares about, without raising if
    optional directories don't exist on disk.
    """
    entries: list[SpriteInventoryEntry] = []
    for root in (_BASELINES_DIR, _VISUAL_REF_DIR, _ASSETS_DIR):
        if root.is_dir():
            entries.extend(inventory_sprites(root, ["*.png"]))
    return entries


_ALL_ENTRIES = _gather_entries()


def test_sprint_2_baselines_directory_present():
    """Sanity: the engine ships baseline PNGs we expect to audit."""
    assert _BASELINES_DIR.is_dir(), (
        f"expected baselines under {_BASELINES_DIR}"
    )
    pngs = list(_BASELINES_DIR.glob("*.png"))
    assert pngs, f"no PNG baselines found under {_BASELINES_DIR}"


def test_sprint_2_inventory_is_nonempty():
    """The sprint must have *something* to audit, otherwise the anchor
    silently does nothing.
    """
    assert _ALL_ENTRIES, (
        "sprint 2 audit found zero PNGs to inspect — check that the "
        "baselines directory still ships in the wheel"
    )


@pytest.mark.parametrize(
    "entry",
    _ALL_ENTRIES,
    ids=[e.path.name for e in _ALL_ENTRIES],
)
def test_sprint_2_sprite_not_critical(entry: SpriteInventoryEntry):
    """No bundled engine sprite should score as ``critical`` (i.e. trip all
    three heuristics — low coverage *and* desaturated *and* tiny).

    Sprites whose name marks them as intentional placeholders are
    ``xfail``ed instead of failing the build, leaving headroom for future
    debug-only fixtures.
    """
    name = entry.path.name.lower()
    if "placeholder" in name or name.startswith("debug_"):
        pytest.xfail(f"intentional placeholder sprite: {entry.path.name}")

    result = assess_quality(entry)
    assert result["recommendation"] != "critical", (
        f"{entry.path} flagged critical by sprite_audit: "
        f"flags={result['flags']} score={result['score']:.3f}"
    )
